dir_gribs=/home/paulo/Documentos/meus_codigos/server_met/data/grib
dir_mapas=/home/paulo/Documentos/meus_codigos/server_met/maps
dir_matrizes=/home/paulo/Documentos/meus_codigos/server_met/data/csv
dir_matrizes_predi=/home/paulo/Documentos/meus_codigos/server_met/data/csv/predi
dir_matrizes_bluesky=/home/paulo/Documentos/meus_codigos/server_met/data/csv/bluesky