dir_gribs=data/gribs
dir_mapas=data/mapasGrib
dir_matrizes=data/matrizGrib
dir_matrizes_predi=data/matrizGrib/predi
dir_matrizes_bluesky=data/matrizGrib/bluesky
dir_analise=data/analise
dir_tmp=data/tmp
db_file=data/met_server.db
